### ISSUE TITLE
NAS autodetect for HCTL mapping

### ISSUE THREAD

**Issue by mnakicevic** [miskcoo/ugreen_dx4600_leds_controller#11]
Modify script so it autodetects NAS and then provide correct HCTL mapping.

This is what I have tried on my DXP6800 Pro and it works:
`if [[ "$(dmidecode --string system-product-name)"="DXP6800 Pro" ]]; then
        echo "Found UGREEN DXP6800 Pro"
        hctl_map=("2:0:0:0" "3:0:0:0" "4:0:0:0" "5:0:0:0" "0:0:0:0" "1:0:0:0")
else
        exit 1
fi;`

**Comment by miskcoo** [comment]
Thanks! I made some adjustment for those who do not have `dmidecode`.
