### ISSUE TITLE
DXP2800

### ISSUE THREAD

**Issue by Balkoth** [miskcoo/ugreen_dx4600_leds_controller#19]
Does this work on the DXP2800?

**Comment by miskcoo** [comment]
I don't know since I don't have such a device. You can test it if you have one.

**Comment by Logian** [comment]
Can confirm that the command-line tool is working and LEDs are fully configurable. Naturally, there's only leds power, netdev, disk1 and disk2 available.

**Comment by miskcoo** [comment]
@Logian can you check whether the product name `dmidecode --string system-product-name` starts with `DXP2800`? I can add this model to the scripts so that you won't see some warning that your device is untested.

**Comment by Logian** [comment]
@miskcoo Output of dmidecode is in fact "DXP2800". Nothing more, nothing less.

**Comment by aqsede** [comment]
I'm lacking in knowledge to enable this. 

I am now able to build the cli on my OMV with debian12. However, still stuck at enabling the LED so it work like normal.
the dkms has errors with kernel headers. So i'm stuck there.
```
nas@omvnas:/home/ugnas/ugreen_dx4600_leds_controller$ sudo dkms add -m led-ugreen -v 0.1
Creating symlink /var/lib/dkms/led-ugreen/0.1/source -> /usr/src/led-ugreen-0.1
nas@omvnas:/home/ugnas/ugreen_dx4600_leds_controller$ sudo dkms build -m led-ugreen -v 0.1
Sign command: /lib/modules/6.1.0-22-amd64/build/scripts/sign-file
Binary /lib/modules/6.1.0-22-amd64/build/scripts/sign-file not found, modules won't be signed
Error! Your kernel headers for kernel 6.1.0-22-amd64 cannot be found at /lib/modules/6.1.0-22-amd64/build or /lib/modules/6.1.0-22-amd64/source.
Please install the linux-headers-6.1.0-22-amd64 package or use the --kernelsourcedir option to tell DKMS where it's located.
```

**Comment by miskcoo** [comment]
> Please install the linux-headers-6.1.0-22-amd64 package or use the --kernelsourcedir option to tell DKMS where it's located.

@aqsede Hi, do you forget to install this `apt install linux-headers-6.1.0-22-amd64`?

**Comment by 0n1cOn3** [comment]
I can confirm that it works flawlessly with the DXP2800 :D 

https://github.com/user-attachments/assets/8e8a91eb-4362-401e-b845-20b40d06c71b

**Comment by miskcoo** [comment]
Hi, @0n1cOn3 @Balkoth, can you have a look on the `system-version` field in `dmidecode` of your DXP2800? Someone reported that the driver won't work in their DXP2800 (#66), and from the UGOS's driver loading script, there seems two different versions, and the one that current driver works may have `system-version= EM_DXP2800`.

```
# dmidecode -s system-product-name
DX4600 Pro
# dmidecode -s system-version
JS1A40043.
```

**Comment by aqsede** [comment]
Mine work flawlessly, kickstarter version on Debian 12 (OMV)

```
# dmidecode -s system-product-name
DXP2800
# dmidecode -s system-version
EM_DXP2800_V1.0.24
```

**Comment by 0n1cOn3** [comment]
> Hi, @0n1cOn3 @Balkoth, can you have a look on the `system-version` field in `dmidecode` of your DXP2800?`.
> 
> ```
> # dmidecode -s system-product-name
> DX4600 Pro
> # dmidecode -s system-version
> JS1A40043.
> ```

Sure!

Here the output what it displays here:

```bash
sanuser@flash01:~$ sudo dmidecode -s system-product-name
DXP2800
sanuser@flash01:~$ sudo dmidecode -s system-version
EM_DXP2800_V1.0.25
sanuser@flash01:~$ 
```

**Comment by Balkoth** [comment]
```
$ sudo dmidecode -s system-product-name
DXP2800
$ sudo dmidecode -s system-version
EM_DXP2800_V1.0.24
```

**Comment by miskcoo** [comment]
Thanks. From what i observed from ugreen's script, when EM_DXP2800 is included in system-version, current driver will continue to work.
